version: '3.0'

services:

  kafka-producer:
    container_name: kafka-producer-project
    build:
      context: ./kafka-producer
      dockerfile: Dockerfile
    depends_on:
      - db
      - kafka
    ports:
      - "8082:8082"
    restart: always

  kafka-consumer:
    container_name: kafka-consumer-project
    build:
      context: ./kafka-consumer
      dockerfile: Dockerfile
    depends_on:
      - db
      - kafka
    ports:
      - "8083:8083"
    restart: always

  zookeeper:
    image: docker.io/bitnami/zookeeper:3.9
    restart: always
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: docker.io/bitnami/kafka:3.4
    restart: always
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_MESSAGE_MAX_BYTES=1205725956
    depends_on:
      - zookeeper

  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=kafka_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

networks:
  my-network:
    driver: bridge