name: CI on merge request
run-name: CI build and test on merge request
on: [ push ]
jobs:
  ci-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64

      - name: setup gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5

      - name: build with gradle
        run: ./gradlew build

      - name: run tests
        run: ./gradlew test