name: Actions CI Aston Kafka
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [ push ]
jobs:
  GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64